# Attention experiment nu/d

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from scipy.linalg import qr

import math
import pandas as pd

In [3]:
import PatnaikPearson as pp
import cupy

In [5]:
N = 200
d = 100
nu_over_d_X = 0.8
nu_over_d_K = 0.8
nu_over_d_Q = 0.8
nu_over_d_V = 0.8
verbose = True
uniform_draws = True
use_pareto = True
use_uniform = False
use_cauchy = False
use_svd = True

xx = pp.attention_experiment_nu_over_d(N, d, nu_over_d_X, nu_over_d_K, nu_over_d_Q, nu_over_d_V, verbose, uniform_draws, use_pareto, use_uniform, use_cauchy, use_svd)

using pareto
[1.00409217 1.00824246 1.01245231 1.01672318 1.02105661]
generate_data_manifold: using svd
using pareto
[1.00409217 1.00824246 1.01245231 1.01672318 1.02105661]
 ** generate_square_weight_matrix: using GPU **
using pareto
[1.00409217 1.00824246 1.01245231 1.01672318 1.02105661]
 ** generate_square_weight_matrix: using GPU **
using pareto
[1.00409217 1.00824246 1.01245231 1.01672318 1.02105661]
 ** generate_square_weight_matrix: using GPU **
alpha_X =  2.436527495621503 , pp_dim_X =  77.73567410968997 , nu_over_d_X =  0.7773567410968997 , implied_alpha_X =  2.310984717152427
alpha_K =  2.436527495621503 , pp_dim_WK =  77.06907402186934 , nu_over_d_WK =  0.7706907402186934 , implied_alpha_K =  2.2774083226675383
alpha_Q =  2.436527495621503 , pp_dim_WQ =  77.19511245967244 , nu_over_d_WQ =  0.7719511245967244 , implied_alpha_Q =  2.283651606314282
alpha_V =  2.436527495621503 , pp_dim_WV =  77.16724516548642 , nu_over_d_WV =  0.7716724516548642 , implied_alpha_V =  2.2822670

In [ ]:
# actual_nu_over_d_AttnQKV =  0.40044720005034806 
# estimate_nu_over_d_AttnQKV =  0.2930212385717338
# pure_estimate_nu_over_d_AttnQKV =  0.292411771408826